### PR TITLE
      update to test against k8s 1.2{1,2,3} kind images 

### PR DESCRIPTION
**Pull request by dholbach**
Addresses: #474 

Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by dholbach** [comment]
Still to be done: update kind cluster 1.20 → 1.23 (once the image is available), so we cover k8s 1.2{1,2,3}

**Comment by ckotzbauer** [comment]
kindest/node v1.23.0 is available.

**Review by ckotzbauer — APPROVED** [review]

**Comment by evrardjp** [comment]
Isn't the PR name confusing? 
"Update testing to cover Kubernetes 1.21->1.23" ?

**Comment by dholbach** [comment]
> Isn't the PR name confusing? "Update testing to cover Kubernetes 1.21->1.23" ?

Yes, sorry - that was the commit message from the first push - I had just updated to the latest image, when 1.23.0 was not available yet.

**Pull request merged**
