### PR TITLE
require DCO from now on

### PR DESCRIPTION
**Pull request by dholbach**
Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Review by evrardjp — COMMENTED** [review]
Two questions.
1) Would it make sense to also add the DCO bot, or do we wait for this to be in the next organisation? 
2) I thought the DCO needed to apply for the CNCF org, which means this PR should land after the move. WDYT?

**Comment by dholbach** [comment]
I added the DCO bot to the `kubereboot` earlier organisation. As the repo transfer is requested now, not sure if it makes sense to enable it to `weaveworks/kured` for the last couple of commits.

**Comment by dholbach** [comment]
I think PRs will need to be re-targeted after the org move, so maybe let's just merge it, as it's just a docs change for now.

**Comment by evrardjp** [comment]
The PRs will be moved over, so I don't think it's a big issue.

**Comment by evrardjp** [comment]
If you don't mind, I will merge https://github.com/weaveworks/kured/pull/637 before this one. Else, the CI has to run again for a doc change.

**Review by evrardjp — APPROVED** [review]

**Pull request merged**
