### PR TITLE
Replaced --annotationTTL with --lockTTL and made it work correctly

### PR DESCRIPTION
**Pull request by mvisonneau**
This is a follow-up on #54, #119 & #143

- I renamed the --annotationTTL flag into --lockTTL as I believe it is a more pertinent nomenclature
- I fixed its implementation as reported not being functional in #143

### CODE REVIEW

**Comment by renaudhager** [comment]
I have tested this, works as expected.

**Comment by bboreham** [comment]
Thanks for the PR.

What are your thoughts regarding it being a breaking change, i.e. anyone who turned on the feature from #54 will now get a hard failure?

**Comment by bboreham** [comment]
I believe this PR changes the semantics from "lock expires at a time set by the locker" to "lock expires when kured thinks it should".
Is that what you intended?  This seems more dangerous.
See discussion at https://github.com/weaveworks/kured/pull/119#discussion_r419966865

**Comment by mvisonneau** [comment]
yes indeed, I believe that this approach allows more flexibility towards changes around the TTL configuration. Specially coming for either a disabled TTL or very long one which would involve a manual edition of the annotation. But I understand that this can lead to conflicts. Happy to revert this part if you feel more comfortable keeping the info on the lock itself.

**Comment by bboreham** [comment]
To me it's less flexible if only one program controls the TTL.  Locks are taken by at least two programs - kured and kubectl.

**Comment by mvisonneau** [comment]
I am not sure to understand what you mean @bboreham? 🤔

**Comment by bboreham** [comment]
Any particular part?  We instruct users to take locks using `kubectl` at https://github.com/weaveworks/kured#disabling-reboots

**Comment by mvisonneau** [comment]
@bboreham indeed thanks, my former changes would have broken this behaviour. I changed the logic around that point back to what is currently in place 👍

**Comment by bboreham** [comment]
I think `Test()` is now wrong in the case that we already hold the lock and it has not expired.

Still looking for your thoughts regarding it being a breaking change, i.e. anyone who turned on the feature from #54 will now get a hard failure.

**Comment by mvisonneau** [comment]
Shouldn't `Test()` return `true` if the lock is being held by the node and not expired yet? 🤔 

#54 never got merge 🤔

**Comment by bboreham** [comment]
OK now I don't know what I was thinking about `Test()`. Sorry.

And I meant #119.

**Comment by mvisonneau** [comment]
ah ok! Well given that #119 is not functional I believe it is fine to take this opportunity to have a more pertinent nomenclature. 🤷

**Comment by bboreham** [comment]
OK, given nobody else noted a concern, let's merge this.

**Comment by dholbach** [comment]
Could it be that the chart needs an update for this?

**Comment by bboreham** [comment]
Nobody should have put the previous one in a chart because it was found to not work about a day after merging it.

**Pull request merged**
