### PR TITLE
Add Microsoft Teams as notification channel

### PR DESCRIPTION
**Pull request by tgarlot**
Fixe #47 

Tested on AKS successfully.

### CODE REVIEW

**Comment by bboreham** [comment]
Thanks for the PR. Seems the code is mostly the same between Slack and Teams - just the body and the url are different - so could that be abstracted out?  Bit more DRY?

Maybe there is a library somewhere that abstracts a bunch of different notification channels?  We don't really want to do all that work in this small project.

**Comment by tgarlot** [comment]
Agreed. I've even put a Teams URL instead of Slack and it work the same :-) Will look a bit further to this PR, see how I can improve it.

**Comment by strowi** [comment]
Very interested in this, whats the status?

**Comment by bboreham** [comment]
> Maybe there is a library somewhere that abstracts a bunch of different notification channels?

#94 offers one possibility.

**Comment by evrardjp** [comment]
What do you think of a generic notification system? (See above ^)

**Comment by Danlewis3** [comment]
+1

**Comment by evrardjp** [comment]
Awesome, thanks for the feedback!

**Comment by dsargent3220** [comment]
Hey guys.  I get the desire to have a DRY, clean, and generic implementation of this, but it hasn't happened, and in the meantime this PR has sat here for over 2 years.  It would be best to implement what has already been written then do the "nice to haves" later.

**Comment by evrardjp** [comment]
@dsargent3220 someone, as of today, is working on a generic implementation in  https://github.com/weaveworks/kured/pull/228. 

Sorry if it takes more time than you would like...

**Comment by tgarlot** [comment]
Will close this PR as there is a better solution being worked out.

**Pull request closed without merging**
