### PR TITLE
Bouncing go.mod with latest kubernetes packages

### PR DESCRIPTION
**Pull request by evrardjp**
Without this patch, go.mod will lag behind for the kubernetes
packages, as it's not automatically tested by dependabot.

We should bump versions with each new minor release of kured.

This should fix it.

### CODE REVIEW

**Comment by evrardjp** [comment]
This will conflict with https://github.com/weaveworks/kured/pull/289, which should merge first.

This is just a first test, to see if everything will still works, thanks to our CI.

**Comment by evrardjp** [comment]
It is properly broken, CI is working!

**Comment by evrardjp** [comment]
Rebased, and introduced a first fix due to deprecation of a field in kubectl pkg.

**Comment by evrardjp** [comment]
Removed DNM now that 1.6.x is out.
Removed WIP as it is now passing CI.

**Comment by evrardjp** [comment]
rebased.

**Review by ckotzbauer — APPROVED** [review]

**Comment by ckotzbauer** [comment]
When this is rebased again, we can merge this.

**Comment by dholbach** [comment]
Just to clarify: this is be prep for kured 1.7.0? k8s 1.21.0 will be released Thursday, April 8th. That'd be in 3 weeks, so sounds fair to me.

**Comment by evrardjp** [comment]
Rebased.

**Pull request merged**
