### PR TITLE
Add `reboot-delay` command line argument

### PR DESCRIPTION
**Pull request by amorey**
Currently, kured issues the system reboot command immediately after
kubectl drain finishes.

This is a problem for processes that need extra time to finish but aren't
running on pods and therefore aren't controlled by kubectl drain (e.g.
de-registering nodes from external load balancers).

This patch solves the problem by introducing a `reboot-delay` command
line argument that can be used to add a delay after kubectl drain
finishes but before the reboot command is issued.

### CODE REVIEW

**Comment by kingdonb** [comment]
(I released the e2e checks that were waiting for approval.) Thanks again!

**Comment by evrardjp** [comment]
Thanks for splitting your PR in two! I will have a look and think of all the things good and bad about this. Eventually. (yes that's my sense of humour!)

**Review by evrardjp — APPROVED** [review]
I think this is fine.

**Comment by evrardjp** [comment]
I realise now it's missing documentation and changes into helm chart + manifest.  Could you do a PR for that @amorey ?

**Pull request merged**
