### PR TITLE
Update k8s dependencies to 0.22.4

### PR DESCRIPTION
**Pull request by dholbach**
Signed-off-by: Daniel Holbach <daniel@weave.works>

### CODE REVIEW

**Comment by jackfrancis** [comment]
Hmm, I'm not able to repro the unit test failure locally

```
Francisbook:kured jackfrancis$ git status
On branch fix-473
Your branch is up to date with 'dholbach/fix-473'.

nothing to commit, working tree clean
Francisbook:kured jackfrancis$ go test -json ./... > test.json
Francisbook:kured jackfrancis$ echo $?
0
```

**Comment by dholbach** [comment]
> Hmm, I'm not able to repro the unit test failure locally
> 
> ```
> Francisbook:kured jackfrancis$ git status
> On branch fix-473
> Your branch is up to date with 'dholbach/fix-473'.
> 
> nothing to commit, working tree clean
> Francisbook:kured jackfrancis$ go test -json ./... > test.json
> Francisbook:kured jackfrancis$ echo $?
> 0
> ```

Looks like we were using the wrong go version.

**Review by ckotzbauer — APPROVED** [review]

**Comment by jackfrancis** [comment]
@dholbach I suspected that, but it wasn't clear how to update it, good work!

(fwiw my local test was 1.17.2)

**Comment by dholbach** [comment]
I noticed it in the log and was confused:

```
 go: downloading github.com/mattn/go-isatty v0.0.12
../../../go/pkg/mod/k8s.io/client-go@v0.22.4/plugin/pkg/client/auth/exec/metrics.go:21:2: package io/fs is not in GOROOT (/opt/hostedtoolcache/go/1.15.15/x64/src/io/fs)
Error: Process completed with exit code 1.
```
https://github.com/weaveworks/kured/runs/4440560752?check_suite_focus=true

That's when I saw that in all other GH Workflows we ensure the right Go version and I was able to copy and paste JP's good work. :-)

**Pull request merged**
