### PR TITLE
Revert parts of #127, move to client-go/kubectl 1.17

### PR DESCRIPTION
**Pull request by dholbach**
Reverts parts of #127 - after the release of kured 1.4.0 we should be able to go back.

This was decided in our meeting
(https://docs.google.com/document/d/1bsHTjHhqaaZ7yJnXF6W8c89UB_yn-OoSZEmDnIP34n8/edit#heading=h.8cgszb6vuhza)

Let's 
- go with supporting Kubernetes 1.1[678] in this release and by basing kured on client-go/kubectl 1.17 for now
- move back to 1.18 once we were able to release [1.4.0](https://github.com/weaveworks/kured/milestone/2)

### CODE REVIEW

**Comment by dholbach** [comment]
Pushing the `docker.io/weaveworks/kured:go-back-to-1.17-3fbc98e` image for testing now.

**Comment by dholbach** [comment]
Testing the last three stable series using minikube:

- [ ] 1.18.2
- [ ] 1.17.5
- [ ] 1.16.9

**Comment by evrardjp** [comment]
On it today.

**Comment by evrardjp** [comment]
Worked even on an old v1.15.11. Trying 1.18.2 now.

**Comment by dholbach** [comment]
I will merge and test in our dev environment tomorrow.

Thanks for reviewing!

**Pull request merged**
