### PR TITLE
Use newer version of k8s client tools

### PR DESCRIPTION
**Pull request by pgroene**
The version of k8s has security vulnerabilities, updating to a newer version

Tested this this version to on our clusters

### CODE REVIEW

**Comment by dholbach** [comment]
Thanks a lot for your PR.

We might need to update to a newer `client-go` and other k8s related bits as well. You might want to look at #75 for the last update Adam did.

**Comment by dholbach** [comment]
@pgroene I took a stab at this - can you take a look at pgroene/kured/pull/1 please?

**Comment by pgroene** [comment]
I also testes the latest version of the alpine image on our servers and it seem to work fine, I can add it to this pull request or create a separate PR for that. @dholbach what would you preferer?

**Comment by dholbach** [comment]
Maybe best to create a separate PR.

Thanks a lot for your testing! :pray:

**Pull request merged**
