### PR TITLE
Fixed a bug where kured was not being scheduled on master nodes properly

### PR DESCRIPTION
**Pull request by ericsuhong**
Fixed a bug where kured was not being scheduled on master nodes properly

### CODE REVIEW

**Comment by bboreham** [comment]
I'm not sure this is a bug.  What was the `value` in your taint?

#88 seems a better way to go, modulo specifying the minimum necessary set

**Comment by evrardjp** [comment]
agreed with @bboreham , again.

**Comment by dholbach** [comment]
Just a quick PSA from me:

- we're hanging out in #kured on Slack
- we're planning a contributors meeting soon: here's the [link to the doodle](https://doodle.com/poll/tuwg4w4mxbbknhe3) to find a good time - be sure to pick your timezone before submitting ([preliminary agenda](https://docs.google.com/document/d/1bsHTjHhqaaZ7yJnXF6W8c89UB_yn-OoSZEmDnIP34n8/edit#))

We'd love to see you there.

**Comment by ericsuhong** [comment]
Kured doesn't by default schedule on master nodes with current deployment.yaml.

We need to add this toleration to make kured schedule on master nodes:
````
tolerations:
        - effect: NoSchedule
          key: node-role.kubernetes.io/master
          operator: "Equal"
          value: "true"
````

**Pull request closed without merging**
