### PR TITLE
Initial Kured Helm-Chart

### PR DESCRIPTION
**Pull request by ckotzbauer**
This PR migrates the kured helm-chart from the stable helm/charts repo, adds GitHub Actions for linting and publishing and made several initial changes to the chart.

## Changes
- Added GitHub Actions to lint, test and release the chart. [`4420dc8`](https://github.com/weaveworks/kured/commit/4420dc82d6f569c54d5cd44dbda1983180aa87fa)
- Added the unchanged chart from helm/charts [`a574a67`](https://github.com/weaveworks/kured/commit/a574a67c618fede0dd7bf9f9c66e0fa0630c62fd)
- Removed the `autolock` feature [`c473caa`](https://github.com/weaveworks/kured/commit/c473caafc8de783ddac486abff8dd5518d9a263c)
- Use a template-function for labels [`02bb6d6`](https://github.com/weaveworks/kured/commit/02bb6d650ef64107c07206012765b1de21f10e57)
- Fix role inconsistencies (verb, psp apigroup) [`d3ea563`](https://github.com/weaveworks/kured/commit/d3ea5639f42c3fb88ee34d5f09626f8707a5bbd9)
- Add affinity support [`ab0b5d1`](https://github.com/weaveworks/kured/commit/ab0b5d137c174a51313a103652dc5ffa0ff484a7)
- Add config-object for cli-flags [`2afa0a9`](https://github.com/weaveworks/kured/commit/2afa0a9da7c3f547d43a2bc280eca240574a83cd)
- Add a Service and ServiceMonitor [`2bb7b79`](https://github.com/weaveworks/kured/commit/2bb7b7937ed72f37e055af764ecac8b39fc89f2c)
- Rearrange default values [`d271165`](https://github.com/weaveworks/kured/commit/d271165496414dfe5c2a08afc77ce3bf56b78362)
- Updated docs [`a815867`](https://github.com/weaveworks/kured/commit/a815867584479859efa73dfe4f1d99e21f866840)

### GitHub Actions
- The action for linting and testing, is triggered for each PR which changes something in the `charts/` directory. The lint-check and a installation with default-values in a kind-cluster has to be successful.
- The release action is triggered on each tag and publishes the current chart to the `gh-pages` branch. (Secret `BOT_GITHUB_TOKEN` is needed @dholbach)

## Follow-up PRs
There are multiple things to do in follow-up PRs when this is merged and tested.
- List this repo on Helm-Hub.
- Deprecate the old chart at helm/charts.

## Follow-up Issues
I will open a issue for discussion:
- Optimizing security of Dockerimage and Helm-Chart (root-user, privileged-permissions, host-pid, allowed volumes in PSP)

## Questions
- With which version the chart should start? :heavy_check_mark: 
- Which maintainers should be listed? :heavy_check_mark: 

Now all values are not changed.

## More information
Ref: #140 
TODO-Lists: [here](https://github.com/weaveworks/kured/issues/140#issue-610640330) and [here](https://github.com/weaveworks/kured/issues/140#issuecomment-645278381).

### CODE REVIEW

**Comment by hSATAC** [comment]
Hi, is it possible to make the `.Values.configuration.blockingPodSelector` an array instead of a single value? So that we can have multiple `--blocking-pod-selector` arguments to act as `OR` condition. [Ref](https://github.com/weaveworks/kured#blocking-reboots-via-pods)

**Comment by dholbach** [comment]
Great work @ckotzbauer - thanks a lot for getting the ball rolling!

Thanks also for breaking this up into individual commits to make things clear. I personally don't have any requests for change as of now.

> (Secret `BOT_GITHUB_TOKEN` is needed @dholbach)

Noted. I'm in conversation with our ops folks.

> Deprecate the old chart at helm/charts.

I noticed https://github.com/helm/charts/issues/21103 where we might want to speak up as well once we're done.

> I will open a issue for discussion:
>    Optimizing security of Dockerimage and Helm-Chart (root-user, privileged-permissions, host-pid, allowed volumes in PSP)

Super. Please use the `helm-chart` label.

> With which version the chart should start?

Can you elaborate? 
- Is this about the `kured` version we want to deploy? If so, the latest, right?
- If this is about the chart version, [current](https://github.com/helm/charts/blob/master/stable/kured/Chart.yaml) seems to be `1.5.1` - shall we go with `2.0.0` to indicate the breaking change?

> Which maintainers should be listed?

If you're still happy to take the lead on the chart, can you list yourself, and maybe me as a backup? I'd hope we could get a few more hands on deck during the next meeting.



I pinged the other Helm chart authors to have a look as well. I might also ping a couple of folks from within Weaveworks to glance over this PR.


Thanks again!

**Comment by ckotzbauer** [comment]
> Noted. I'm in conversation with our ops folks.

Great!

> I noticed helm/charts#21103 where we might want to speak up as well once we're done.

Oh, good catch. I didn't know about this issue :smile:

**Comment by ckotzbauer** [comment]
@hSATAC 
Thanks, for that hint. I don't know if kured supports the usage of this flag multiple times. If it is supported, then an array is much more elegant here. The same should be done for `--reboot-days` to stay consistent.

**Comment by hSATAC** [comment]
@ckotzbauer Thanks for the reply. I am not sure about the `--reboot-days` but according to the README, multiple `--blocking-pod-selector` parameters is supported. Please refer to https://github.com/weaveworks/kured#blocking-reboots-via-pods

Thanks for your great work again 💯

**Comment by ckotzbauer** [comment]
@hSATAC 
Sorry, I missed the crucial sentence there. :smile: Yes, than it's possible and I will modify the chart accordingly.
Reading the code-docs of `StringArrayVar` (`--blocking-pod-selector`) and `StringSliceVar` (`--reboot-days`) of the pflag-library it is possible to use the `--reboot-days` flag multiple times too. Can anyone confirm?

**Comment by ckotzbauer** [comment]
I just tested the cli-parameter by myself and it worked for both. Updated the chart.

**Pull request merged**
