### PR TITLE
Updated helm charts with new message template flag

### PR DESCRIPTION
**Pull request by atighineanu**
Updated helm charts with new message template flag
+ bumped chart version

### CODE REVIEW

**Review by ckotzbauer — CHANGES_REQUESTED** [review]
Can you add the flag to the daemonset and the chart Readme too? Otherwise the change has no effect.

**Comment by atighineanu** [comment]
> Can you add the flag to the daemonset and the chart Readme too? Otherwise the change has no effect.

Done.

**Review by ckotzbauer — APPROVED** [review]

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by atighineanu** [comment]
Somethin else I need to do here? @ckotzbauer @jackfrancis @dholbach

**Comment by ckotzbauer** [comment]
@jackfrancis We have to release a Kured patch-release now, the chart points to the current Kured release which doesn't have the new feature. Helm-PRs which needs Code-Changes can only be merged when there was a new Kured release.

**Comment by jackfrancis** [comment]
@ckotzbauer thanks for the clarification

going forward let's add a /hold gesture (or hold tag) to indicate that a PR shouldn't be merged, hopefully I won't do this again! :/

**Comment by ckotzbauer** [comment]
that's a good idea 👍 
I can try to cut a release in the evening.

**Pull request merged**
