### PR TITLE
update chart definition to include --notify-url

### PR DESCRIPTION
**Pull request by atighineanu**
Updating chart definition for --notify-url, following the PR: #315
Issue(s): https://github.com/weaveworks/kured/issues/332

### CODE REVIEW

**Review by ckotzbauer — APPROVED** [review]

**Review by evrardjp — APPROVED** [review]
LGTM. Will only pass on releasing, but it's good already.

Let's hope github will be smart enough to do rebasing on its own if any changes come up before this one merges :)

**Comment by evrardjp** [comment]
That's interesting, how is this passing? : )

**Comment by evrardjp** [comment]
oh yeah it makes sense, the image used is the image for which the code was built, so HEAD of this branch. 
I wonder if, for helm chart changes, we should have a different behaviour, and only test existing images?

**Comment by atighineanu** [comment]
> ~oh yeah it makes sense, the image used IS the image directly built on this PR (HEAD of this branch). Because the CI overrides the image used, this passes.~
> 
> ~I wonder if, for helm chart changes, we should have a different behaviour, and only test existing images? It's maybe too convoluted...~
> 
> Edit: I have noticed our chart testing action should have failed. Its logs show it's not working as expected, but the job is still green. Next to this, I have proposed a test coverage change to be more clear, as what I mentioned above is still true, but isn't obvious to me, even if I was the original author of that testing (I guess my memory is becoming bad with time >< )

Related PR: https://github.com/weaveworks/kured/pull/348

**Pull request merged**
