### PR TITLE
Added possibility to mount volumes

### PR DESCRIPTION
**Pull request by renaudhager**
Hi all,

This PR allow to configures volumes and volumeMounts this is useful to mount a specific folder for the sentinel file.

Let me know if anything needs to be changed.

Thanks

### CODE REVIEW

**Review by ckotzbauer — CHANGES_REQUESTED** [review]
Thanks for your PR. This looks pretty good. The only missing thing is the parameter descriptions in the README.md of the chart. Could you please add them?

**Comment by renaudhager** [comment]
> Thanks for your PR. This looks pretty good. The only missing thing is the parameter descriptions in the README.md of the chart. Could you please add them?

Done, let me know if you need anything else.

**Review by ckotzbauer — APPROVED** [review]
Thanks!
I saw, that there're conflicts now. Could you please do a rebase? When this is done, the PR is ready to merge.

**Comment by renaudhager** [comment]
Hi @ckotzbauer,

It should be fixed. Let me know if you need anything else.

Thanks.

**Pull request merged**
