### PR TITLE
Make go lint on cmd folder happier

### PR DESCRIPTION
**Pull request by evrardjp**
This does a few non important cleanups for readability.
It also removes the prom-active-alerts command which is not used,
not tested, and currently broken.

### CODE REVIEW

**Comment by evrardjp** [comment]
Added bboreham for the review, more particularily because of the removal of prom-active-alerts which we discussed in the kured slack.

**Comment by evrardjp** [comment]
Disclaimer: This has not been tested using my CI tooling. Not that I expect any failure from this, though.

**Comment by bboreham** [comment]
Code changes look good, thanks.
I would have mentioned the `v1` change in the commit message, in case someone is trying to understand it in a few years.
Suggest removing `prom-active-alerts` from `.gitignore` and anywhere else it is referenced.

**Comment by evrardjp** [comment]
Will do, and adapt the commit message.

**Comment by evrardjp** [comment]
I have split into two commits, so it's easier to see what is what.

**Review by bboreham — APPROVED** [review]
Excellent work, thank you!

**Pull request merged**
