### PR TITLE
Prepare 1.5.1 release

### PR DESCRIPTION
**Pull request by dholbach**
Tested with `minikube`, k8s versions 1.17.14, 1.18.12, 1.19.4.

Commits since 1.5.0 by bboreham, dholbach, evrardjp, mvisonneau, smueller18:

# Breaking changes
`--annotationTTL` was renamed to `--lockTTL` (Helm chart values accordingly).

# Bug fixes
- #213 and #238: Replaced --annotationTTL with --lockTTL and made it work correctly
- #237: Drain: allow pods grace period to terminate
- #166: Remove quote for parameter alert-filter-regexp

# Clean Up
- #217: Clean up deps, update docs to explain state post-210
- #210: feature: Remove kubectl bin
- #198: fix: Follow DKL-DI-0004 guideline
- #194: add missing quote - thanks Karan Arora for reporting

# Release automation
- #185: Release helper
- #221: Add Lint job in github actions
- #222: Make go lint on pkg folder happier 
- #215: Make go lint on cmd folder happier

### CODE REVIEW

**Comment by dholbach** [comment]
Is the version check of the lint-chart action useful?

**Comment by ckotzbauer** [comment]
Yes, we have to bump the chart to 2.2.2

**Comment by dholbach** [comment]
I was just asking because the 2.2.1 chart was never released, right? https://github.com/weaveworks/kured/tree/gh-pages

**Comment by ckotzbauer** [comment]
ah, you are right. Then we can ignore this lint error.

**Comment by evrardjp** [comment]
Yes, our pipeline can still be improved further until it goes full automatic :)

**Comment by evrardjp** [comment]
I will test today

**Comment by dholbach** [comment]
I tested this in our Dev environment too - so far so good. ✨

**Review by evrardjp — APPROVED** [review]
Worked for me. No strong opinion on the helm chart bump.

**Review by ckotzbauer — APPROVED** [review]
LGTM. Tested locally. Would not bump the chart again, as it's not necessary.

**Comment by dholbach** [comment]
Could it be that #213 needs an update in the chart?

**Comment by dholbach** [comment]
Retested https://github.com/weaveworks/kured/commit/4b1e4036e3352b1ca64bd4ad59f36730775f218e using minikube on latest supported k8s versions: :heavy_check_mark: 

Still needs testing in our dev environment.

**Comment by ckotzbauer** [comment]
> Could it be that #213 needs an update in the chart?

Yes, the config-param needs to be changed.

**Pull request merged**
