### PR TITLE
Bump to newer golang version

### PR DESCRIPTION
**Pull request by evrardjp**

### CODE REVIEW

**Comment by dholbach** [comment]
`/k/kubernetes` uses [1.13 still](https://github.com/kubernetes/kubernetes/blob/master/go.mod#L7), so I'm not sure about moving right now. Can we push this further down the line?

**Comment by evrardjp** [comment]
Yes, no urgency.

**Comment by dholbach** [comment]
k8s 1.19 moved to to go 1.15, so we'll be able to bump this for the kured release (1.6.0?) that brings k8s 1.20 support.

**Comment by evrardjp** [comment]
Yes, I can probably do another patch.

**Pull request closed without merging**
