### PR TITLE
add ms teams notifications

### PR DESCRIPTION
**Pull request by yershalom**

### CODE REVIEW

**Review by rossdotpink — APPROVED** [review]

**Comment by rossdotpink** [comment]
LGTM

**Review by wwmoraes — APPROVED** [review]
LGTM

**Comment by dholbach** [comment]
Have you seen https://github.com/weaveworks/kured/pull/228, which would enable other notifications as well? AFAICS it would just need rebasing?

**Comment by jackfrancis** [comment]
@yershalom @rossdotpink @dholbach what do you think about this approach instead?:

https://github.com/weaveworks/kured/pull/315

**Comment by dholbach** [comment]
I like @atighineanu 's work and we tested the patch together a bit when we the PR first came up. It looks fairly comprehensive and like a good, more general solution.

**Comment by yershalom** [comment]
@dholbach It's better approach, I'm closing this.
Thanks yall

**Pull request closed without merging**
