### PR TITLE
Updated Kubernetes to 1.21

### LINKED ISSUE #425: Update k8s deps to 1.21
Update k8s deps to 1.21

### PR DESCRIPTION
**Pull request by ckotzbauer**
- Package updated to 1.21.x
- Added tests for 1.22
- Dropped tests for 1.19

fixes #425 #426

### CODE REVIEW

**Comment by dholbach** [comment]
Rebased this on `main` and bumped to go 1.16. I'm getting the following stack trace with kind and k8s 1.21:

```
❯ kubectl logs -f kured-86v8s -n kube-system
time="2021-09-08T09:30:02Z" level=info msg="Kubernetes Reboot Daemon: k8s-1.21-f182695"
time="2021-09-08T09:30:02Z" level=info msg="Node ID: kind-control-plane3"
time="2021-09-08T09:30:02Z" level=info msg="Lock Annotation: kube-system/kured:weave.works/kured-node-lock"
time="2021-09-08T09:30:02Z" level=info msg="Lock TTL not set, lock will remain until being released"
time="2021-09-08T09:30:02Z" level=info msg="Lock release delay not set, lock will be released immediately after rebooting"
time="2021-09-08T09:30:02Z" level=info msg="PreferNoSchedule taint: "
time="2021-09-08T09:30:02Z" level=info msg="Blocking Pod Selectors: []"
time="2021-09-08T09:30:02Z" level=info msg="Reboot schedule: SunMonTueWedThuFriSat between 00:00 and 23:59 UTC"
time="2021-09-08T09:30:02Z" level=info msg="Reboot check command: [test -f /var/run/reboot-required] every 1m0s"
time="2021-09-08T09:30:02Z" level=info msg="Reboot command: [/bin/systemctl reboot]"
time="2021-09-08T09:30:02Z" level=info msg="Holding lock"
time="2021-09-08T09:30:02Z" level=info msg="Uncordoning node kind-control-plane3"
time="2021-09-08T09:30:02Z" level=info msg="instantiating helper with client &{%!s(*discovery.DiscoveryClient=&{0xc0000ff9a0 /api}) %!s(*v1.AdmissionregistrationV1Client=&{0xc000403cc0}) %!s(*v1beta1.AdmissionregistrationV1beta1Client=&{0xc000403e00}) %!s(*v1alpha1.InternalV1alpha1Client=&{0xc000403f40}) %!s(*v1.AppsV1Client=&{0xc0000fe000}) %!s(*v1beta1.AppsV1beta1Client=&{0xc0000fe0a0}) %!s(*v1beta2.AppsV1beta2Client=&{0xc0000fe140}) %!s(*v1.AuthenticationV1Client=&{0xc0000fe1e0}) %!s(*v1beta1.AuthenticationV1beta1Client=&{0xc0000fe280}) %!s(*v1.AuthorizationV1Client=&{0xc0000fe320}) %!s(*v1beta1.AuthorizationV1beta1Client=&{0xc0000fe3c0}) %!s(*v1.AutoscalingV1Client=&{0xc0000fe460}) %!s(*v2beta1.AutoscalingV2beta1Client=&{0xc0000fe500}) %!s(*v2beta2.AutoscalingV2beta2Client=&{0xc0000fe5a0}) %!s(*v1.BatchV1Client=&{0xc0000fe640}) %!s(*v1beta1.BatchV1beta1Client=&{0xc0000fe6e0}) %!s(*v1.CertificatesV1Client=&{0xc0000fe780}) %!s(*v1beta1.CertificatesV1beta1Client=&{0xc0000fe820}) %!s(*v1beta1.CoordinationV1beta1Client=&{0xc0000fe8c0}) %!s(*v1.CoordinationV1Client=&{0xc0000fe960}) %!s(*v1.CoreV1Client=&{0xc0000fea00}) %!s(*v1.DiscoveryV1Client=&{0xc0000feaa0}) %!s(*v1beta1.DiscoveryV1beta1Client=&{0xc0000feb40}) %!s(*v1.EventsV1Client=&{0xc0000febe0}) %!s(*v1beta1.EventsV1beta1Client=&{0xc0000fec80}) %!s(*v1beta1.ExtensionsV1beta1Client=&{0xc0000fed20}) %!s(*v1alpha1.FlowcontrolV1alpha1Client=&{0xc0000fedc0}) %!s(*v1beta1.FlowcontrolV1beta1Client=&{0xc0000fee60}) %!s(*v1.NetworkingV1Client=&{0xc0000fef00}) %!s(*v1beta1.NetworkingV1beta1Client=&{0xc0000fefa0}) %!s(*v1.NodeV1Client=&{0xc0000ff040}) %!s(*v1alpha1.NodeV1alpha1Client=&{0xc0000ff0e0}) %!s(*v1beta1.NodeV1beta1Client=&{0xc0000ff180}) %!s(*v1.PolicyV1Client=&{0xc0000ff220}) %!s(*v1beta1.PolicyV1beta1Client=&{0xc0000ff2c0}) %!s(*v1.RbacV1Client=&{0xc0000ff360}) %!s(*v1beta1.RbacV1beta1Client=&{0xc0000ff400}) %!s(*v1alpha1.RbacV1alpha1Client=&{0xc0000ff4a0}) %!s(*v1alpha1.SchedulingV1alpha1Client=&{0xc0000ff540}) %!s(*v1beta1.SchedulingV1beta1Client=&{0xc0000ff5e0}) %!s(*v1.SchedulingV1Client=&{0xc0000ff680}) %!s(*v1beta1.StorageV1beta1Client=&{0xc0000ff720}) %!s(*v1.StorageV1Client=&{0xc0000ff7c0}) %!s(*v1alpha1.StorageV1alpha1Client=&{0xc0000ff860})}"
time="2021-09-08T09:30:02Z" level=info msg="drainer set up &{<nil> %!s(*kubernetes.Clientset=&{0xc0002d01a0 0xc0002b7f10 0xc0002b7f70 0xc0002b7fd0 0xc0004d4030 0xc0004d40b0 0xc0004d4120 0xc0004d41a0 0xc0004d4210 0xc0004d4270 0xc0004d4300 0xc0004d4360 0xc0004d43d0 0xc0004d4450 0xc0004d44b0 0xc0004d4540 0xc0004d45a0 0xc0004d4600 0xc0004d4690 0xc0004d4700 0xc0004d4760 0xc0004d47c0 0xc0004d4820 0xc0004d4880 0xc0004d4900 0xc0004d4960 0xc0004d49d0 0xc0004d4a50 0xc0004d4ac0 0xc0004d4b30 0xc0004d4b90 0xc0004d4c20 0xc0004d4c80 0xc0004d4d10 0xc0004d4d70 0xc0004d4df0 0xc0004d4e50 0xc0004d4ec0 0xc0004d4f20 0xc0004d4f80 0xc0004d4fe0 0xc0004d5040 0xc0004d50a0 0xc0004d5100}) %!s(bool=false) %!s(int=0) %!s(bool=false) %!s(bool=false) 0s %!s(bool=false)   %!s(bool=false) %!s(int=0) [] %!s(*os.File=&{0xc00012a060}) %!s(*os.File=&{0xc00012a0c0}) %!s(util.DryRunStrategy=0) %!s(*resource.DryRunVerifier=<nil>) %!s(func(*v1.Pod, bool)=<nil>)}"
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x127549a]

goroutine 21 [running]:
golang.org/x/time/rate.(*Limiter).WaitN(0xc000415e00, 0x0, 0x0, 0x1, 0x0, 0x0)
	/home/daniel/go/pkg/mod/golang.org/x/time@v0.0.0-20210220033141-f8bda1e9f3ba/rate/rate.go:237 +0xba
golang.org/x/time/rate.(*Limiter).Wait(...)
	/home/daniel/go/pkg/mod/golang.org/x/time@v0.0.0-20210220033141-f8bda1e9f3ba/rate/rate.go:219
k8s.io/client-go/util/flowcontrol.(*tokenBucketRateLimiter).Wait(0xc00040d220, 0x0, 0x0, 0x0, 0x0)
	/home/daniel/go/pkg/mod/k8s.io/client-go@v0.21.4/util/flowcontrol/throttle.go:106 +0x4b
k8s.io/client-go/rest.(*Request).tryThrottleWithInfo(0xc0000ce5a0, 0x0, 0x0, 0x0, 0x0, 0x42, 0x40)
	/home/daniel/go/pkg/mod/k8s.io/client-go@v0.21.4/rest/request.go:587 +0xa5
k8s.io/client-go/rest.(*Request).tryThrottle(...)
	/home/daniel/go/pkg/mod/k8s.io/client-go@v0.21.4/rest/request.go:613
k8s.io/client-go/rest.(*Request).request(0xc0000ce5a0, 0x0, 0x0, 0xc000267728, 0x0, 0x0)
	/home/daniel/go/pkg/mod/k8s.io/client-go@v0.21.4/rest/request.go:873 +0x2fc
k8s.io/client-go/rest.(*Request).Do(0xc0000ce5a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/home/daniel/go/pkg/mod/k8s.io/client-go@v0.21.4/rest/request.go:980 +0xf1
k8s.io/client-go/kubernetes/typed/core/v1.(*nodes).Patch(0xc0006a1f30, 0x0, 0x0, 0xc0005b06c0, 0x13, 0x1ac283a, 0x26, 0xc000738ea0, 0x1f, 0x20, ...)
	/home/daniel/go/pkg/mod/k8s.io/client-go@v0.21.4/kubernetes/typed/core/v1/node.go:186 +0x237
k8s.io/kubectl/pkg/drain.(*CordonHelper).PatchOrReplaceWithContext(0xc000267b10, 0x0, 0x0, 0x1cf2e68, 0xc000343600, 0x0, 0x19d6a80, 0x1, 0xc000267b00, 0x47811c)
	/home/daniel/go/pkg/mod/k8s.io/kubectl@v0.21.4/pkg/drain/cordon.go:102 +0x416
k8s.io/kubectl/pkg/drain.RunCordonOrUncordon(0xc0001d9790, 0xc000174c00, 0x1aa6a00, 0x11, 0xc000267bc0)
	/home/daniel/go/pkg/mod/k8s.io/kubectl@v0.21.4/pkg/drain/default.go:60 +0xb3
main.uncordon(0xc000343600, 0xc000174c00)
	/home/daniel/dev/kured/cmd/kured/main.go:407 +0x245
main.rebootAsRequired(0xc00004000e, 0x13, 0xc00053e180, 0x5, 0x6, 0xc00053e120, 0x6, 0x6, 0xc00021c600, 0x0, ...)
	/home/daniel/dev/kured/cmd/kured/main.go:506 +0xf98
created by main.root
	/home/daniel/dev/kured/cmd/kured/main.go:669 +0xc05

kured on  k8s-1.21 [!⇕] via 🐹 v1.16.7 
❯ git diff
diff --git a/cmd/kured/main.go b/cmd/kured/main.go
index d7759f6..92bab4f 100644
--- a/cmd/kured/main.go
+++ b/cmd/kured/main.go
@@ -397,11 +397,13 @@ func drain(client *kubernetes.Clientset, node *v1.Node) {
 func uncordon(client *kubernetes.Clientset, node *v1.Node) {
        nodename := node.GetName()
        log.Infof("Uncordoning node %s", nodename)
+       log.Infof("instantiating helper with client %s", client)
        drainer := &kubectldrain.Helper{
                Client: client,
                ErrOut: os.Stderr,
                Out:    os.Stdout,
        }
+       log.Infof("drainer set up %s", drainer)
        if err := kubectldrain.RunCordonOrUncordon(drainer, node, false); err != nil {
                log.Fatalf("Error uncordonning %s: %v", nodename, err)
        }

```

As you can see, I added two debug statements.

**Comment by ckotzbauer** [comment]
@dholbach Should we create an issue on the kubernetes repo? I'm not sure how we should fix this.

**Comment by dholbach** [comment]
We could try out 0.21.5 as well.

**Comment by dholbach** [comment]
Can you rebase on current `main`?

**Review by dholbach — APPROVED** [review]

**Pull request merged**
