### PR TITLE
Clarify and simplify tests

### PR DESCRIPTION
**Pull request by evrardjp**
Without this, we get multiple questions about our testing.
This should help clarify the tests and our coverage by:
- Simplifying our coverage
- Documenting better the purpose of each workflow file
- Documenting our testing and development activities better.

### CODE REVIEW

**Review by ckotzbauer — APPROVED** [review]
I did not review the pipeline in detail, but the changes are looking good to me. The doc additions are very helpful :+1:

**Comment by evrardjp** [comment]
Interestingly, those jobs have failed, so I am wondering if reliability of manifest deploys is fine.

**Review by ckotzbauer — APPROVED** [review]

**Comment by evrardjp** [comment]
Rebased.

**Comment by evrardjp** [comment]
Rebased.

**Pull request merged**
