### PR TITLE
add a drain timeout

### PR DESCRIPTION
**Pull request by flbla**
same as https://github.com/weaveworks/kured/pull/79 but with latest changes

Closes: #78

### CODE REVIEW

**Comment by evrardjp** [comment]
@bboreham I added you in the reviewer list, since you already reviewed the PR 79 here https://github.com/weaveworks/kured/pull/79

**Comment by evrardjp** [comment]
@flbla Can you mention in your github PR: "Closes: #78" ? This will auto-close the related issue upon merge. Thank you.

**Comment by flbla** [comment]
Closes: #78

**Comment by flbla** [comment]
@evrardjp : I rebased my branch and added the close comment

**Comment by dholbach** [comment]
Sorry. Can you please retarget your branch to be merged into `main` please?

**Pull request closed without merging**
