### PR TITLE
Use clean patch to update node labels. Fixes #553

### LINKED ISSUE #553: Error updating labels after reboot
```
kured-8jmzc kured time="2022-05-19T15:14:32Z" level=error msg="Error updating node labels zalando=ready  via k8s API: Operation cannot be fulfilled on nodes \"us01vlk8sw00011.auto.saas-n.com\": the object has been modified; please apply your changes to the latest version and try again"

```
Caused by bug in #541. I will fix.

### PR DESCRIPTION
**Pull request by liger1978**

### CODE REVIEW

**Comment by liger1978** [comment]
@ckotzbauer @jackfrancis I uncovered issue #553 following PR #541 This PR fixes it. Please review.

**Review by jackfrancis — APPROVED** [review]
lgtm

**Comment by liger1978** [comment]
Can we get it merged?

**Review by ckotzbauer — APPROVED** [review]

**Comment by ckotzbauer** [comment]
@liger1978 There should always be enough time for other maintainers to have a look before a PR is merged 😉

**Comment by liger1978** [comment]
@ckotzbauer Sure, of course. Please don't take my keenness as rudeness. Thanks!

**Pull request merged**
