### PR TITLE
Update kured-ds.yaml

### PR DESCRIPTION
**Pull request by evrardjp**
Without this patch, it's not clear that we added command line
arguments recently. This should expose our latest changes in the
future released manifest.

### CODE REVIEW

**Comment by evrardjp** [comment]
I re-ordered those to be equal to the order in the code.

I am thinking of reordering them by function or alphabetically, but I think that can be done later. As long as we don't miss anything.

**Comment by dholbach** [comment]
Hum... why code-order? Not sure if that's what users expect?

**Comment by evrardjp** [comment]
I used the code order so I didn't forget one line :) Those things are easy to miss.

I am happy to change the order to something that makes more sense to our users.
Do you have anything to suggest? It needs to be clear so that new contributors KNOW how to add their flag, if necessary.

**Comment by evrardjp** [comment]
One way is around integrations: split the arguments around notifications, reboot blockers, reboot triggers. But I am not super convinced yet.

**Comment by evrardjp** [comment]
Still, in the meantime, it's worth being more complete than what we currently have.

I mentioned this gap into the PR to clarify the contributions and test coverage.

**Review by ckotzbauer — APPROVED** [review]

**Pull request merged**
