### PR TITLE
Update golang and x/net to avoid CVE in our builds

### PR DESCRIPTION
**Pull request by evrardjp**

### CODE REVIEW

**Comment by evrardjp** [comment]
Interestingly, the gh action doesn't take latest 1.18, and takes 1.18.5...

**Comment by ckotzbauer** [comment]
@evrardjp See #519, I discovered this problem in the past already. The fix seems not to work then :disappointed:

**Comment by evrardjp** [comment]
> @evrardjp See #519, I discovered this problem in the past already. The fix seems not to work then disappointed

Commit number 2 seems to fix the problem, and uses the latest 1.18. 
Is that what you meant?

**Comment by evrardjp** [comment]
For clarity's sake, I don't think the CVE really impacts us strongly, but it's worth updating anyway.

**Review by jackfrancis — APPROVED** [review]
lgtm

**Review by ckotzbauer — APPROVED** [review]

**Pull request merged**
