### PR TITLE
Update dev docs

### PR DESCRIPTION
**Pull request by dholbach**
Some file names changed, so I went and fixed the dev docs.

### CODE REVIEW

**Review by evrardjp — CHANGES_REQUESTED** [review]
Can we separate the go.mod and go.sum changes from this PR?

I don't see why they are bundled in this PR.

**Comment by dholbach** [comment]
Sure, I can - I just noticed that VSCode was complaining that the `go.*` were out of sync...........

**Comment by evrardjp** [comment]
> 
> 
> Sure, I can - I just noticed that VSCode was complaining that the `go.*` were out of sync...........

haha, same for me :)

**Review by evrardjp — APPROVED** [review]
LGTM

**Pull request merged**
